openapi: 3.0.2
info:
  description: |
    PayGate is a RESTful API enabling first-party Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transfers to be created without a deep understanding of a full NACHA file specification. First-party transfers initiate at an Originating Depository Financial Institution (ODFI) and are sent off to other Financial Institutions.

    Refer to the [client endpoints](https://moov-io.github.io/paygate/) for customr facing operations.
  version: v1
  title: Paygate Admin API
  contact:
    url: https://github.com/moov-io/paygate
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:9092
    description: Local development

tags:
  - name: Admin
    description: PayGate admin endpoints for checking the running status.
  - name: Transfers
    description: Transfer objects created to move funds between two Customers and their Accounts. The API allows you to create them, inspect their status and delete pending transfers.

paths:
  /live:
    get:
      tags: [Admin]
      summary: Get Liveness Probes
      description: Get the status of each depdendency
      operationId: getLivenessProbes
      responses:
        '200':
          description: The status of dependencies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessProbes'
        '400':
          description: An error occurred when checking dependencies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessProbes'
  /version:
    get:
      tags: [Admin]
      summary: Get Version
      description: Show the current version of PayGate
      operationId: getVersion
      responses:
        '200':
          description: The current version running
          content:
            text/plain:
              schema:
                type: string
                example: v0.7.1

  /trigger-cutoff:
    put:
      tags: [Transfers]
      summary: Initiate cutoff processing
      operationId: triggerCutoffProcessing
      description: Starts processing like it's a cutoff window approaching. This involves merging transfers into files, upload attempts, along with inbound file download processing.
      responses:
        '200':
          description: Processing was successful
        '400':
          description: See error message
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/moov-io/base/master/api/common.yaml#/components/schemas/Error'

  /transfers/{transferId}/status:
    put:
      tags: [Transfers]
      summary: Update Transfer status
      description: |+
          Updates a Transfer status for a transferID.

          PENDING transfers may be updated to: CANCELED or REVIEWABLE.
          REVIEWABLE transfers may be updated to: CANCELED or PENDING.
      operationId: updateTransferStatus
      parameters:
        - name: transferId
          in: path
          description: transferID that identifies the Transfer
          required: true
          schema:
            type: string
            example: e0d54e15
        - name: X-Request-ID
          in: header
          description: Optional requestID allows application developer to trace requests through the systems logs
          example: rs4f9915
          schema:
            type: string
        - name: X-Organization
          in: header
          required: true
          description: Value used to separate and identify models
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTransferStatus'
      responses:
        '200':
          description: Transfer with updated status
        '400':
          description: See error message
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/moov-io/base/master/api/common.yaml#/components/schemas/Error'

components:
  schemas:
    LivenessProbes:
      properties:
        customers:
          type: string
          description: Either an error from checking Customers or good as a string.
          example: good
    UpdateTransferStatus:
      properties:
        status:
          $ref: 'https://raw.githubusercontent.com/moov-io/paygate/master/api/client.yaml#/components/schemas/TransferStatus'
